spring:
  application:
    name: micro-db
  boot:
    admin:
      client:
        url: http://spring-admin-service/
        instance:
          prefer-ip: true
  config:
    import: optional:configserver:http://spring-config-service/
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:3306/db_micro
    username: micro
    password: micro123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-registry-service/

jpa:
  hibernate:
    ddl-auto: update


