spring:
  application:
    name: micro-db
  boot:
    admin:
      client:
        url: http://spring-admin.lab.pl
  config:
    import: optional:configserver:http://spring-config.lab.pl/
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:10.0.0.26}:3306/db_micro
    username: micro
    password: micro123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-registry.lab.pl/

jpa:
  hibernate:
    ddl-auto: update


